# Generated by Django 4.1.4 on 2022-12-28 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_profile_location_skills"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Skills",
            new_name="Skill",
        ),
    ]
