# Generated by Django 4.1.4 on 2023-01-22 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_rename_skills_skill"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"ordering": ["name"]},
        ),
    ]
