# Generated by Django 4.1.4 on 2022-12-19 20:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("demo_link", models.CharField(blank=True, max_length=2000, null=True)),
                (
                    "source_link",
                    models.CharField(blank=True, max_length=2000, null=True),
                ),
                ("vote_total", models.IntegerField(blank=True, default=0, null=True)),
                ("vote_ratio", models.IntegerField(blank=True, default=0, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("dd5b8e23-5529-4287-977b-db326f45aa40"),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                ("body", models.TextField(blank=True, null=True)),
                (
                    "value",
                    models.CharField(
                        choices=[("up", "Up vote"), ("down", "Down vote")],
                        max_length=200,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("ca0ca163-655f-4f9f-b5c5-c90f55d9eca5"),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("name", models.CharField(max_length=200)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("6167b33c-b060-4aa8-b05d-440058c327cf"),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Projects",
        ),
        migrations.AddField(
            model_name="project",
            name="tag",
            field=models.ManyToManyField(blank=True, to="projects.tag"),
        ),
    ]
