# Generated by Django 4.1.4 on 2022-12-19 20:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_project_review_tag_delete_projects_project_tag"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="tag",
            new_name="tags",
        ),
        migrations.AlterField(
            model_name="project",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("8ba23edd-743d-4e78-9799-f53eb9b918a1"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("fa036e90-532d-4752-b2ce-94e05d9ba92f"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("d2cbdad1-7698-44bf-b24a-d3a6c58c5e4e"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
